### PR TITLE
chore(resources): Optimize general config

### PR DESCRIPTION
**Pull request by p-w-p**
Use the following  for reference:
`*.lan` https://github.com/openwrt/openwrt/blob/main/package/base-files/files/etc/ethers
`*.internal` https://www.icann.org/en/board-activities-and-meetings/materials/approved-resolutions-special-meeting-of-the-icann-board-29-07-2024-en
`fe80::/10, fc00::/7, ff00::/8` https://en.wikipedia.org/wiki/Reserved_IP_addresses
`https://doh.pub/dns-query`https://docs.dnspod.cn/public-dns/public-dns-illustrate/
`https://dns.alidns.com/dns-query`https://alidns.com/

### CODE REVIEW

**Comment by Johnshall** [comment]
Thanks for your commit!
I think it is same to use either `dns.alidns.com` or `223.5.5.5`, and so does the dnspob. The paradox occurs when looking for the IP of `dns.alidns.com` or `doh.pub`, as Shadowrocket will use other DNS providers to find them, which may include local DNS provider or other unencrypted DNS providers.

The [document of alidns](https://alidns.com/articles/6018321800a44d0e45e90d71) also describes this:
```
DNS over HTTPs（DoH）的URI接口 ：（仅提供TLS API）

https://dns.alidns.com/dns-query?
[https://](https://223.5.5.5/dns-query?)alidns_ip[/dns-query?](https://223.5.5.5/dns-query?)
注意：其中alidns_ip是dns.alidns.com 的A和AAAA记录，可以是以下四个地址之一 ：223.5.5.5，223.6.6.6，2400:3200::1, 2400:3200:baba::1.
```

To figure out how to get a TLS certificate and establish TLS connections, please refer to this [document](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-tls/#how-it-works).

**Comment by p-w-p** [comment]
> Thanks for your commit! I think it is same to use either or , and so does the dnspob. The paradox occurs when looking for the IP of or , as Shadowrocket will use other DNS providers to find them, which may include local DNS provider or other unencrypted DNS providers.`dns.alidns.com``223.5.5.5``dns.alidns.com``doh.pub`
> 
> The [document of alidns](https://alidns.com/articles/6018321800a44d0e45e90d71) also describes this:
> 
> ```
> DNS over HTTPs（DoH）的URI接口 ：（仅提供TLS API）
> 
> https://dns.alidns.com/dns-query?
> [https://](https://223.5.5.5/dns-query?)alidns_ip[/dns-query?](https://223.5.5.5/dns-query?)
> 注意：其中alidns_ip是dns.alidns.com 的A和AAAA记录，可以是以下四个地址之一 ：223.5.5.5，223.6.6.6，2400:3200::1, 2400:3200:baba::1.
> ```
> 
> To figure out how to get a TLS certificate and establish TLS connections, please refer to this [document](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-tls/#how-it-works).

Thanks for the reply!
This change is primarily for IPv6-only environments. In this case, https://dns.alidns.com/dns-query is preferable to https://223.5.5.5/dns-query. Of course, if you don’t agree with this change, I’ll undo it.
BTW, IPv4 special address blocks can also be further simplified. Should I handle that as well, or complete the IPv6 special address blocks that haven’t been included in the pull request?

**Comment by Johnshall** [comment]
Sorry for the delay.😥
Actually I haven't realize the fast development of IPv6. Thanks for your reminder, and I do think `https://dns.alidns.com/dns-query` is better than `https://223.5.5.5/dns-query` for both IPv4 and IPv6 users.

> BTW, IPv4 special address blocks can also be further simplified. Should I handle that as well, or complete the IPv6 special address blocks that haven’t been included in the pull request?

I would greatly appreciate if you could implement this for the repository. Your work is always perfect!

**Comment by p-w-p** [comment]
> Sorry for the delay.😥 Actually I haven't realize the fast development of IPv6. Thanks for your reminder, and I do think `https://dns.alidns.com/dns-query` is better than `https://223.5.5.5/dns-query` for both IPv4 and IPv6 users.
> 
> > BTW, IPv4 special address blocks can also be further simplified. Should I handle that as well, or complete the IPv6 special address blocks that haven’t been included in the pull request?
> 
> I would greatly appreciate if you could implement this for the repository. Your work is always perfect!

Which one do you prefer?
```
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, fe80::/10, fc00::/7, localhost, *.local, *.lan, *.internal, e.crashlytics.com, captive.apple.com, sequoia.apple.com, seed-sequoia.siri.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,::/128,::1/128,fe80::/10,fc00::/7,ff00::/8,::ffff:0:0/96,::ffff:0:0:0/96,64:ff9b::/96,64:ff9b:1::/48,100::/64,2001::/32,2001:20::/28,2001:db8::/32,2002::/16,3fff::/20,5f00::/16
```
or
```
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, fe80::/10, fc00::/7, localhost, *.local, *.lan, *.internal, e.crashlytics.com, captive.apple.com, sequoia.apple.com, seed-sequoia.siri.apple.com
bypass-tun = 127.0.0.0/8,169.254.0.0/16,10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,255.255.255.255/32,::1/128,fe80::/10,fc00::/7,ff00::/8
```
I prefer the more streamlined one because it only keeps the situations you’re likely to encounter in daily life.

**Comment by Metaphorme** [comment]
To make it clear, the forther remove these addresses as followed:
 192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,::/128,::ffff:0:0:0/96,64:ff9b::/96,64:ff9b:1::/48,100::/64,2001::/32,2001:20::/28,2001:db8::/32,2002::/16,3fff::/20,5f00::/16
 
All of these belong to reserved IP addresses or SRv6. On the one hand, they should bypass the tun to avoid some unpredictability errors. On the other hand, they are not used very frequently. I think it might be more reliable to keep them.

**Comment by Johnshall** [comment]
To make it clear, the forther remove these addresses as follows:
 192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,::/128,::ffff:0:0:0/96,64:ff9b::/96,64:ff9b:1::/48,100::/64,2001::/32,2001:20::/28,2001:db8::/32,2002::/16,3fff::/20,5f00::/16
 
All of these belong to reserved IP addresses or SRv6. On the one hand, they should bypass the tun to avoid some unpredictability errors. On the other hand, they are not used very frequently. I think it might be more reliable to keep them.

**Comment by p-w-p** [comment]
> To make it clear, the forther remove these addresses as follows: 192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,::/128,::ffff:0:0:0/96,64:ff9b::/96,64:ff9b:1::/48,100::/64,2001::/32,2001:20::/28,2001:db8::/32,2002::/16,3fff::/20,5f00::/16
> 
> All of these belong to reserved IP addresses or SRv6. On the one hand, they should bypass the tun to avoid some unpredictability errors. On the other hand, they are not used very frequently. I think it might be more reliable to keep them.

I have modified the code according to your expectations. It’s ready for review.

**Comment by Johnshall** [comment]
It's great fun to work with you! So appreciate for your help!

**Pull request merged**
